--------------------------- MODULE TraceRaft ---------------------------
(***************************************************************************)
(* Trace validation: does Raft.tla permit a run the implementation actually *)
(* performed?                                                              *)
(*                                                                         *)
(* This is the step that connects the two halves of P7. Model checking      *)
(* Raft.tla says the specification is sound. The fault sweep and the        *)
(* state-space search say the implementation survives what they threw at    *)
(* it. Neither says the two are *related*, and that gap is where a          *)
(* specification quietly becomes decoration -- it is entirely possible to   *)
(* have a verified spec and an implementation doing something else, and     *)
(* nothing in either activity notices.                                     *)
(*                                                                         *)
(* `TraceLog.tla` is generated by anvil_trace_export from one run of        *)
(* anvil::raft::RaftNode, written in this specification's variable          *)
(* vocabulary. What follows replays it.                                    *)
(*                                                                         *)
(***************************************************************************)
(* How the granularity mismatch is handled, which is the whole problem      *)
(***************************************************************************)
(*                                                                         *)
(* One implementation transition is one node consuming one input and        *)
(* running its Ready loop to completion. The specification's actions are    *)
(* finer: a message arriving at a higher term is `UpdateTerm` and *then* a  *)
(* handler; a candidate collecting its last vote is                         *)
(* `HandleRequestVoteResponse` and *then* `BecomeLeader`; every message the *)
(* node then sends is its own action. So "assert Next holds between         *)
(* consecutive observed states" is simply false, and a validation built     *)
(* that way would report the implementation as non-conforming for a reason  *)
(* that is about neither of them.                                          *)
(*                                                                         *)
(* Two halves to the answer, and the first does most of the work:           *)
(*                                                                         *)
(*   The exporter decomposes the sends. After a transition it writes one    *)
(*   observed state for the node's new internal state, then one more per    *)
(*   message the transition put on the wire, added in order. Each of those  *)
(*   is exactly one AppendEntries / Heartbeat / RequestVote action. That is *)
(*   a projection and not an invention: the implementation really did       *)
(*   produce those messages, in that order, from that state.               *)
(*                                                                         *)
(*   `Hide` below allows a bounded number of unobserved steps between       *)
(*   observed ones, for the receive-side pairs that genuinely cannot be     *)
(*   separated. The bound is small -- MaxHidden, three in the .cfg --       *)
(*   because with the sends already decomposed there is little left to      *)
(*   hide. Without the decomposition it would need to be six or more, and   *)
(*   TLC would enumerate the entire successor set six times per checkpoint. *)
(*                                                                         *)
(***************************************************************************)
(* How to read the result                                                  *)
(*                                                                         *)
(* `NotReplayed` is an invariant that is REQUIRED TO BE VIOLATED. Violating *)
(* it means TLC found a path through the specification that reaches the end *)
(* of the trace -- which is conformance. If TLC instead completes with no   *)
(* violation, it means the replay got stuck: the implementation did         *)
(* something at some step that the specification does not permit, and that  *)
(* is a real finding about one of the two.                                 *)
(*                                                                         *)
(* Inverted checks are worth flagging, and this one is inverted because     *)
(* "some behaviour exists" is an existential claim and TLC's native         *)
(* question is universal. tools/tlc.sh states the expectation in its table  *)
(* so the inversion lives in exactly one place.                            *)
(***************************************************************************)

EXTENDS Raft, TraceLog

CONSTANT MaxHidden,
         \* Prints each checkpoint as it is reached. A stalled replay is
         \* otherwise a number with no story attached, and "it stopped at 54"
         \* is not a diagnosis. TraceRaftDebug.cfg sets this.
         Verbose

VARIABLES ti,      \* how far through the trace the replay has got
          hidden   \* consecutive unobserved steps taken since the last one

\* Every specification variable equals what was observed at trace position k.
\* Written over primed variables so TLC can use them as assignments rather than
\* as a filter -- which is why `Matches` is conjoined *before* `Next` below, and
\* that ordering is the difference between a run that finishes and one that
\* enumerates the whole successor set at every step.
Matches(k) ==
    /\ currentTerm'      = Trace[k].currentTerm
    /\ state'            = Trace[k].state
    /\ votedFor'         = Trace[k].votedFor
    /\ log'              = Trace[k].log
    /\ commitIndex'      = Trace[k].commitIndex
    /\ votesGranted'     = Trace[k].votesGranted
    /\ messages'         = Trace[k].messages
    /\ elections'        = Trace[k].elections
    /\ committedLog'     = Trace[k].committedLog
    /\ commitRuleBroken' = Trace[k].commitRuleBroken

TraceInit ==
    /\ ti     = 1
    /\ hidden = 0
    /\ currentTerm      = Trace[1].currentTerm
    /\ state            = Trace[1].state
    /\ votedFor         = Trace[1].votedFor
    /\ log              = Trace[1].log
    /\ commitIndex      = Trace[1].commitIndex
    /\ votesGranted     = Trace[1].votesGranted
    /\ messages         = Trace[1].messages
    /\ elections        = Trace[1].elections
    /\ committedLog     = Trace[1].committedLog
    /\ commitRuleBroken = Trace[1].commitRuleBroken

\* The next observed state is reached, and the specification permits the step.
\*
\* `UNCHANGED vars` is the other half and it is not a fudge. The implementation
\* takes steps this specification has no vocabulary for -- a tick that does not
\* reach the election timeout is the common one -- and a step that changes
\* nothing the specification can see is a *stuttering* step, which every TLA+
\* specification permits by definition: `[][Next]_vars` is satisfied by leaving
\* `vars` alone. Refinement is exactly the claim that the implementation's steps
\* are specification steps *or* stutters, so excluding them would be asserting
\* something stronger than refinement and getting a failure for it. Which is
\* what happened: without this, the very first tick stalled the replay.
Advance ==
    /\ ti < Len(Trace)
    /\ Matches(ti + 1)
    /\ (Next \/ UNCHANGED vars)
    /\ ti' = ti + 1
    /\ hidden' = 0
    /\ (IF Verbose THEN PrintT(<<"reached", ti + 1>>) ELSE TRUE)

\* An intermediate step the exporter could not observe, because the
\* implementation performed it inside a single transition.
Hide ==
    /\ hidden < MaxHidden
    /\ Next
    /\ ti' = ti
    /\ hidden' = hidden + 1

TraceNext == Advance \/ Hide

TraceSpec == TraceInit /\ [][TraceNext]_<<vars, ti, hidden>>

\* REQUIRED TO BE VIOLATED. See the header.
NotReplayed == ti < Len(Trace)

=============================================================================
